import { General } from "../entities.js";

export const GeneralHelper = {
  createEmptyGeneral(id: number, name: string): General {
    return {
      id,
      name,
      ownerId: 0,
      nationId: 0,
      cityId: 0,
      npc: 2,
      troopId: 0,
      gold: 0,
      rice: 500,
      leadership: 50,
      leadershipExp: 0,
      strength: 50,
      strengthExp: 0,
      intel: 50,
      intelExp: 0,
      politics: 50,
      politicsExp: 0,
      charm: 50,
      charmExp: 0,
      injury: 0,
      experience: 0,
      dedication: 0,
      officerLevel: 1,
      officerCity: 0,
      recentWar: 0,
      crew: 0,
      crewType: 0,
      train: 0,
      atmos: 0,
      dex: {},
      age: 20,
      startAge: 20,
      belong: 0,
      betray: 0,
      dedLevel: 0,
      expLevel: 0,
      bornYear: 0,
      deadYear: 0,
      special: "None",
      specAge: 0,
      special2: "None",
      specAge2: 0,
      weapon: "",
      book: "",
      horse: "",
      item: "",
      turnTime: new Date(),
      recentWarTime: null,
      makeLimit: 0,
      killTurn: 0,
      block: 0,
      defenceTrain: 0,
      tournamentState: 0,
      lastTurn: {},
      meta: {},
      penalty: {},
      officerLock: 0,
    };
  },
};
