import { describe, it, expect } from "vitest";
import { LiteHashDRBG, RandUtil } from "@sammo/common";
import { WorldSnapshot } from "../entities.js";
import { GeneralSpyCommand } from "./GeneralSpyCommand.js";

describe("GeneralSpyCommand", () => {
  const seed = "test-spy-seed";
  const rng = new LiteHashDRBG(seed);
  const rand = new RandUtil(rng);

  const mockSnapshot: WorldSnapshot = {
    generals: {
      1: {
        id: 1,
        name: "유비",
        nationId: 1,
        cityId: 1,
        gold: 1000,
        rice: 1000,
        intel: 80,
        leadership: 80,
        strength: 80,
        politics: 80,
        charm: 99,
        officerLevel: 12,
        officerCity: 0,
        experience: 0,
        dedication: 0,
        turnTime: new Date(),
        killTurn: 0,
        meta: {},
        penalty: {},
        leadershipExp: 0,
        strengthExp: 0,
        intelExp: 0,
        politicsExp: 0,
        charmExp: 0,
        injury: 0,
        crew: 0,
        crewType: 0,
        train: 0,
        atmos: 0,
        age: 20,
        special: "None",
        specAge: 0,
        special2: "None",
        specAge2: 0,
        recentWar: 0,
        block: 0,
        ownerId: 0,
        bornYear: 0,
        deadYear: 0,
        weapon: "",
        book: "",
        horse: "",
        item: "",
        recentWarTime: null,
        makeLimit: 0,
        troopId: 0,
        dex: {},
        defenceTrain: 80,
        tournamentState: 0,
        lastTurn: {},
      },
    },
    nations: {
      1: {
        id: 1,
        name: "유비군",
        chiefGeneralId: 1,
        level: 1,
        color: "#FFF",
        capitalCityId: 1,
        gold: 0,
        rice: 0,
        rate: 0,
        rateTmp: 0,
        tech: 0,
        power: 0,
        typeCode: "che_중립",
        gennum: 1,
        spy: {},
        meta: {},
        aux: {},
        warState: 0,
        strategicCmdLimit: 0,
        surrenderLimit: 0,
        scoutLevel: 0,
      },
      2: {
        id: 2,
        name: "조조군",
        chiefGeneralId: 2,
        level: 1,
        color: "#F00",
        capitalCityId: 2,
        gold: 0,
        rice: 0,
        rate: 0,
        rateTmp: 0,
        tech: 0,
        power: 0,
        typeCode: "che_중립",
        gennum: 1,
        spy: {},
        meta: {},
        aux: {},
        warState: 0,
        strategicCmdLimit: 0,
        surrenderLimit: 0,
        scoutLevel: 0,
      },
    },
    cities: {
      1: {
        id: 1,
        name: "평원",
        nationId: 1,
        level: 5,
        supply: 1,
        pop: 1000,
        popMax: 1000,
        agri: 1000,
        agriMax: 1000,
        comm: 1000,
        commMax: 1000,
        secu: 100,
        secuMax: 100,
        def: 100,
        defMax: 100,
        wall: 100,
        wallMax: 100,
        trust: 100,
        gold: 0,
        rice: 0,
        region: 1,
        state: 0,
        term: 0,
        conflict: {},
        meta: {},
        front: 0,
      },
      2: {
        id: 2,
        name: "업",
        nationId: 2,
        level: 5,
        supply: 1,
        pop: 1000,
        popMax: 1000,
        agri: 1000,
        agriMax: 1000,
        comm: 1000,
        commMax: 1000,
        secu: 100,
        secuMax: 100,
        def: 100,
        defMax: 100,
        wall: 100,
        wallMax: 100,
        trust: 100,
        gold: 0,
        rice: 0,
        region: 1,
        state: 0,
        term: 0,
        conflict: {},
        meta: {},
        front: 0,
      },
    },
    diplomacy: {},
    troops: {},
    messages: {},
    gameTime: { year: 184, month: 1 },
    env: { develcost: 100 },
  };

  it("타국 도시에 첩보를 실행하면 성공해야 함", () => {
    const cmd = new GeneralSpyCommand();
    const delta = cmd.run(rand, mockSnapshot, 1, { destCityId: 2 });

    expect(delta.logs?.general?.[1][0]).toContain("정보를");
    expect(delta.generals?.[1]?.gold).toBeLessThan(1000);
  });

  it("아국 도시에 첩보를 실행하면 실패해야 함", () => {
    const cmd = new GeneralSpyCommand();
    const delta = cmd.run(rand, mockSnapshot, 1, { destCityId: 1 });

    expect(delta.logs?.general?.[1][0]).toContain("첩보 실패: 아국입니다");
  });
});
