import { describe, it, expect } from "vitest";
import { LiteHashDRBG, RandUtil } from "@sammo/common";
import { WorldSnapshot } from "../entities.js";
import { GeneralGiftCommand } from "./GeneralGiftCommand.js";

describe("GeneralGiftCommand", () => {
  const seed = "test-gift-seed";
  const rng = new LiteHashDRBG(seed);
  const rand = new RandUtil(rng);

  const mockSnapshot: WorldSnapshot = {
    generals: {
      1: {
        id: 1,
        name: "보내는장수",
        nationId: 1,
        cityId: 1,
        troopId: 0,
        gold: 5000,
        rice: 5000,
        leadership: 50,
        leadershipExp: 0,
        strength: 50,
        strengthExp: 0,
        intel: 50,
        intelExp: 0,
        politics: 50,
        politicsExp: 0,
        charm: 50,
        charmExp: 0,
        injury: 0,
        experience: 1000,
        dedication: 1000,
        crew: 0,
        crewType: 0,
        train: 0,
        atmos: 0,
        age: 20,
        turnTime: new Date(),
        killTurn: 0,
        meta: {},
        penalty: {},
        officerLevel: 1,
        officerCity: 1,
        ownerId: 1,
        bornYear: 180,
        deadYear: 280,
        weapon: "",
        book: "",
        horse: "",
        item: "",
        recentWarTime: null,
        makeLimit: 0,
        block: 0,
        recentWar: 0,
        dex: {},
        special: "",
        specAge: 0,
        special2: "",
        specAge2: 0,
        defenceTrain: 80,
        tournamentState: 0,
        lastTurn: {},
        npc: 0,
        startAge: 20,
        belong: 1,
        betray: 0,
        dedLevel: 0,
        expLevel: 0,
        officerLock: 0,
      },
      2: {
        id: 2,
        name: "받는장수",
        nationId: 1,
        cityId: 1,
        troopId: 0,
        gold: 100,
        rice: 100,
        leadership: 50,
        leadershipExp: 0,
        strength: 50,
        strengthExp: 0,
        intel: 50,
        intelExp: 0,
        politics: 50,
        politicsExp: 0,
        charm: 50,
        charmExp: 0,
        injury: 0,
        experience: 1000,
        dedication: 1000,
        crew: 0,
        crewType: 0,
        train: 0,
        atmos: 0,
        age: 20,
        turnTime: new Date(),
        killTurn: 0,
        meta: {},
        penalty: {},
        officerLevel: 1,
        officerCity: 1,
        ownerId: 2,
        bornYear: 180,
        deadYear: 280,
        weapon: "",
        book: "",
        horse: "",
        item: "",
        recentWarTime: null,
        makeLimit: 0,
        block: 0,
        recentWar: 0,
        dex: {},
        special: "",
        specAge: 0,
        special2: "",
        specAge2: 0,
        defenceTrain: 80,
        tournamentState: 0,
        lastTurn: {},
        npc: 0,
        startAge: 20,
        belong: 1,
        betray: 0,
        dedLevel: 0,
        expLevel: 0,
        officerLock: 0,
      },
    },
    nations: {
      1: {
        id: 1,
        name: "국가1",
        color: "#FF0000",
        capitalCityId: 1,
        gold: 10000,
        rice: 10000,
        rate: 10,
        rateTmp: 10,
        tech: 0,
        power: 1000,
        level: 1,
        gennum: 2,
        typeCode: "che_중립",
        scoutLevel: 0,
        warState: 0,
        strategicCmdLimit: 36,
        surrenderLimit: 72,
        spy: {},
        meta: {},
        aux: {},
        chiefGeneralId: 1,
      },
    },
    cities: {
      1: {
        id: 1,
        name: "도시1",
        nationId: 1,
        supply: 1,
        pop: 10000,
        popMax: 10000,
        agri: 5000,
        agriMax: 10000,
        comm: 5000,
        commMax: 10000,
        secu: 100,
        secuMax: 100,
        def: 1000,
        defMax: 1000,
        wall: 1000,
        wallMax: 1000,
        trust: 100,
        trade: 100,
        dead: 0,
        region: 1,
        state: 0,
        term: 0,
        conflict: {},
        meta: {},
        level: 5,
        front: 0,
      },
    },
    diplomacy: {},
    troops: {},
    messages: {},
    gameTime: { year: 184, month: 1 },
    env: {},
    generalTurns: {},
  };

  it("금 1000을 증여해야 함", () => {
    const cmd = new GeneralGiftCommand();
    const delta = cmd.run(rand, mockSnapshot, 1, {
      isGold: true,
      amount: 1000,
      destGeneralId: 2,
    });

    expect(delta.generals?.[1]?.gold).toBe(4000);
    expect(delta.generals?.[2]?.gold).toBe(1100);
    expect(delta.logs?.general?.[1]?.[0]).toContain("받는장수에게 금 1,000을 증여했습니다.");
    expect(delta.logs?.general?.[2]?.[0]).toContain("보내는장수에게서 금 1,000을 증여받았습니다.");
  });

  it("최소 유지 비용(금 0, 쌀 500)을 제외하고 증여해야 함", () => {
    const cmd = new GeneralGiftCommand();

    // 쌀 5000 보유 중, 5000 증여 시도 -> 4500만 증여됨
    const delta = cmd.run(rand, mockSnapshot, 1, {
      isGold: false,
      amount: 5000,
      destGeneralId: 2,
    });

    expect(delta.generals?.[1]?.rice).toBe(500); // 5000 - 4500
    expect(delta.generals?.[2]?.rice).toBe(4600); // 100 + 4500
    expect(delta.logs?.general?.[1]?.[0]).toContain("받는장수에게 쌀 4,500을 증여했습니다.");
  });
});
